const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8'),context={};vm.createContext(context);vm.runInContext(html.match(/<script id="model">([\s\S]*?)<\/script>/)[1]+'\nthis.api={DEFAULTS,calculate,solve,npv,irr};',context);const{DEFAULTS:D,calculate,solve,npv,irr}=context.api;
const close=(a,b,t=1e-5)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
assert.equal(D.area,1334);let a=calculate(D);close(a.land,106720000);close(a.saleable,667);close(a.revenue,200100000);close(a.cost,149766520);close(a.profit,50333480);close(a.interest,0);close(a.eqIRR,a.unIRR);close(a.rows.at(-1).cum,a.profit);assert.equal(a.rows.filter(r=>r.development>0).length,12);assert.equal(a.rows.filter(r=>r.sales>0).length,36);assert.equal(a.rows.find(r=>r.sales>0).m,12);
let b=calculate({...D,landPrice:100000});close(b.land,133400000);close(b.tax,19943300);close(b.net,113456700);close(b.cost,178207400);close(b.profit,21892600);close(calculate({...D,basis:200000000}).tax,0);
for(const p of[D,{...D,landPrice:100000},{...D,landDebt:60,devDebt:50},{...D,growth:5}]){const r=calculate(p),s=solve(p);close(calculate({...p,plotPrice:s.breakEven}).profit,0,.1);close(npv(calculate({...p,plotPrice:s.hurdlePrice}).eq,p.hurdle/100),0,.1);close(npv(calculate({...p,landPrice:s.ceiling}).eq,p.hurdle/100),0,.1);close(r.rows.at(-1).debt,0);close(r.rows.at(-1).cum,r.profit,.001);assert.ok(r.rows.every(x=>x.debt>=-.001));}
const debt=calculate({...D,landDebt:100,devDebt:100,plotPrice:0});assert.ok(debt.interest>0);close(debt.rows.at(-1).debt,0);assert.equal(debt.payback,null);assert.equal(irr([-1,-2]),null);assert.equal(irr([-100,250,-100]),null);assert.equal(solve({...D,dev:100000000,plotPrice:0}).ceiling,null);
console.log('All model tests passed. Defaults use 1,334 cents.');for(const price of[80000,100000]){const p={...D,landPrice:price},r=calculate(p),s=solve(p);console.log(JSON.stringify({landPrice:price,costCr:r.cost/1e7,profitCr:r.profit/1e7,IRR:r.unIRR*100,hurdlePlot:s.hurdlePrice,ceiling:s.ceiling}));}
const elements=new Map(),storage=new Map();context.document={getElementById(id){if(!elements.has(id))elements.set(id,{addEventListener(){},innerHTML:'',textContent:''});return elements.get(id)},addEventListener(){}};context.localStorage={setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)};context.setTimeout=setTimeout;context.clearTimeout=clearTimeout;vm.runInContext([...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)][1][1],context);assert.match(elements.get('ceiling').textContent,/69,711/);elements.get('pin').onclick();elements.get('save').onclick();elements.get('reset').onclick();elements.get('load').onclick();assert.match(elements.get('scenarios').innerHTML,/Scenario 1/);assert.match(elements.get('status').textContent,/loaded/);console.log('UI render and scenario storage smoke checks passed.');
